## Main Optimization
<br>

#### **Author**: Philipp Hege
#### **Date**: 04.07.2023
#### **Purpose**: Total optimization of the outer optimization (including the inner optimization).

___________
### 0 - Imports
Import all neccessary modules and packages.

In [1]:
import pandas as pd
import os
import datetime

from Main_Optimization import Optimization

___________
### 1 - Data preprocessing

In [2]:
data_directory = '' #'00_data'

df = pd.read_excel(os.path.join(data_directory, 'Auftragsfolgen ohne MaschStatus-20230622.xlsx'),
                   header=0)

# change data types
df['Start'] = pd.to_datetime(df['Start'])
df['Ende'] = pd.to_datetime(df['Ende'])
df['LTermin'] = pd.to_datetime(df['LTermin'])
df['Lieferdatum_Rohmaterial'] = pd.to_datetime(df['Lieferdatum_Rohmaterial'])

# build and rename columns
df['Release_Date'] = df['Lieferdatum_Rohmaterial'] + pd.Timedelta(days=1)
df = df.rename(columns = {'LTermin': 'Due_Date',
                          'Fefco_Teil': 'FEFCO_Teil'}) # rename, because the new Schulte data has different column names

# divide data by machines: Each machine gets a unique df
data = {}

for machine in df.Maschine.unique():
    data[machine] = df[df.Maschine == machine].sort_values('Start').reset_index(drop=True)

machine = 'SL-7'
production_start = pd.Timestamp(datetime.date(2017, 3, 10)) # datetime.date(2015, 1, 14)
# get data which is released before production start and has a due data not before one day after production start
df_test = data[machine][(data[machine].Release_Date <= production_start) & (data[machine].Due_Date >= production_start + pd.Timedelta(days=2))].reset_index(drop=True)
df_test.head()

,AKNR,TeilNr,SchrittNr,FEFCO_Teil,ArtNr_Teil,ID_Druck,Druckflaeche,Bogen_Laenge_Brutto,Bogen_Breite_Brutto,Maschine,...,Menge_Ist,Bemerkung,Due_Date,KndNr,Suchname,Lieferdatum_Rohmaterial,BE_Erledigt,Start,Ende,Release_Date
0,55797,1,1,0410 H,18867,1,0.10,898.0,791.0,SL-7,...,4250,Druckfarbe: schwarz Klischee-Nr.: 1300 LK FS...,2017-03-15,12516,STEENS GROUP A/S,2017-03-02,1,2017-03-06 19:15:26,2017-03-06 21:00:00,2017-03-03
1,55798,1,1,0410 H,18869,1,0.10,1255.0,1240.0,SL-7,...,3550,Druckfarbe: schwarz Klischee-Nr.: 1300 LK FS...,2017-03-15,12516,STEENS GROUP A/S,2017-03-02,1,2017-03-07 09:15:43,2017-03-07 09:35:58,2017-03-03
2,55922,1,1,0410 H,21601,1,0.05,1245.0,1226.0,SL-7,...,525,Klischee-Nr. 1293 B ( am 18.02.15 bei Weichert...,2017-03-20,12300,BMG,2017-03-09,1,2017-03-07 10:55:23,2017-03-07 11:20:14,2017-03-10
3,55934,1,1,0454 man,11491,1,0.01,747.0,1825.0,SL-7,...,2065,"nur Nr.Druck ; Druckfarbe : schwarz , Nr.-Druc...",2017-03-15,10304,SEDUS,2017-03-07,1,2017-03-08 19:15:21,2017-03-08 20:23:55,2017-03-08
4,56190,1,1,412,22496,0,NaN,1571.0,1509.0,SL-7,...,1045,Ohne Druck Mit Griffloch mittig 30x90 mm kei...,2017-03-16,14367,PANTHER DISPLAY,2017-03-07,1,2017-03-09 08:01:51,2017-03-09 08:56:20,2017-03-08

___________
### 2 - Running the whole optimization

In [3]:
schedule, meta_params  = Optimization(df_test)

[I 2023-07-24 14:41:52,009] A new study created in memory with name: no-name-5e858a47-b7e4-40f7-99de-ee0f4aeb8f3e

Restricted license - for non-production use only - expires 2024-10-28

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

[I 2023-07-24 14:42:02,228] Trial 0 finished with value: 0.8846153846153846 and parameters: {'Makespan': 2.9841028891971573, 'Lateness': 5.325796731365145, 'PointEstimatorAddOn': 1.3682411728894466}. Best is trial 0 with value: 0.8846153846153846.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

[I 2023-07-24 14:42:12,431] Trial 1 finished with value: 0.8846153846153846 and parameters: {'Makespan': 4.133853161783809, 'Lateness': 7.661348803961578, 'PointEstimatorAddOn': 1.3192692922573404}. Best is trial 0 with value: 0.8846153846153846.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

[I 2023-07-24 14:42:22,592] Trial 2 finished with value: 0.8846153846153846 and parameters: {'Makespan': 5.148600348251992, 'Lateness': 2.500904355483626, 'PointEstimatorAddOn': 0.9410348633909206}. Best is trial 0 with value: 0.8846153846153846.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

[I 2023-07-24 14:42:32,759] Trial 3 finished with value: 0.8461538461538461 and parameters: {'Makespan': 3.998066315283374, 'Lateness': 9.90710898743924, 'PointEstimatorAddOn': 1.4634018568444138}. Best is trial 3 with value: 0.8461538461538461.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

[I 2023-07-24 14:42:42,904] Trial 4 finished with value: 0.7692307692307693 and parameters: {'Makespan': 7.587376806140487, 'Lateness': 0.6711218992518204, 'PointEstimatorAddOn': 1.4023734648455237}. Best is trial 4 with value: 0.7692307692307693.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

[I 2023-07-24 14:42:53,095] Trial 5 finished with value: 0.8076923076923077 and parameters: {'Makespan': 2.9026009919817954, 'Lateness': 9.709806443121858, 'PointEstimatorAddOn': 1.1115656411380246}. Best is trial 4 with value: 0.7692307692307693.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

[I 2023-07-24 14:43:03,265] Trial 6 finished with value: 0.8076923076923077 and parameters: {'Makespan': 6.6468508807971425, 'Lateness': 4.582758026186767, 'PointEstimatorAddOn': 1.1331903423478473}. Best is trial 4 with value: 0.7692307692307693.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

[I 2023-07-24 14:43:13,430] Trial 7 finished with value: 0.8461538461538461 and parameters: {'Makespan': 0.6922913539756949, 'Lateness': 6.922856736338928, 'PointEstimatorAddOn': 1.395247350351049}. Best is trial 4 with value: 0.7692307692307693.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

[I 2023-07-24 14:43:23,618] Trial 8 finished with value: 0.8461538461538461 and parameters: {'Makespan': 6.859332411853862, 'Lateness': 7.03498579973731, 'PointEstimatorAddOn': 1.1089135304936626}. Best is trial 4 with value: 0.7692307692307693.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

[I 2023-07-24 14:43:33,780] Trial 9 finished with value: 0.8846153846153846 and parameters: {'Makespan': 0.44462790363891513, 'Lateness': 1.4629274699949495, 'PointEstimatorAddOn': 1.2908566475440248}. Best is trial 4 with value: 0.7692307692307693.
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

StartTime[jj]: <gurobi.Var *Awaiting Model Update*>
StartTime[ii]: <gurobi.Var *Awaiting Model Update*>
processing_time: 30
setup_time[ii+1][jj]: 0.0
bigM: 100000
X: <gurobi.Var *Awaiting Model Update*>
End

In [4]:
meta_params

{'Makespan': 7.587376806140487,
 'Lateness': 0.6711218992518204,
 'PointEstimatorAddOn': 1.4023734648455237}

In [5]:
schedule

,AKNR,TeilNr,SchrittNr,Start,Ende,Ruestzeit_Ist,Lieferdatum_Rohmaterial,Due_Date
JOB_ID,,,,,,,,
55798_1_1,55798,1,1,2017-03-03 01:02:26.399999999,2017-03-03 02:37:26.400000000,62.439999,2017-03-02,2017-03-15
55797_1_1,55797,1,1,2017-03-03 03:39:52.800000000,2017-03-03 05:32:52.800000000,62.439999,2017-03-02,2017-03-15
55690_1_1,55690,1,1,2017-03-07 00:00:00.000000000,2017-03-07 00:30:00.000000000,62.000000,2017-03-06,2017-03-13
54855_1_1,54855,1,1,2017-03-07 01:19:31.200000000,2017-03-07 02:37:31.200000000,49.520000,2017-03-06,2017-03-13
56190_1_1,56190,1,1,2017-03-08 00:00:00.000000000,2017-03-08 00:39:00.000000000,57.900002,2017-03-07,2017-03-16
55934_1_1,55934,1,1,2017-03-08 01:46:01.200000000,2017-03-08 03:34:01.200000000,67.019997,2017-03-07,2017-03-15
55588_1_1,55588,1,1,2017-03-09 00:00:00.000000000,2017-03-09 00:28:00.000000000,67.019997,2017-03-08,2017-03-13
55592_1_1,55592,1,1,2017-03-09 01:14:31.200000000,2017-03-09 01:41:31.200000000,46.520000,2017-03-08,2017-03-13
55537_1_1,55537,1,1,2017-03-09 02:43:57.600000000,2017-03-09 03:07:57.600000000,62.439999,2017-03-08,2017-03-20
55538_1_1,55538,1,1,2017-03-09 04:10:24.600000000,2017-03-09 04:40:24.600000000,62.439999,2017-03-08,2017-03-20
55224_1_1,55224,1,1,2017-03-09 05:42:51.000000000,2017-03-09 06:28:51.000000000,62.439999,2017-03-08,2017-03-14
56188_1_1,56188,1,1,2017-03-09 07:31:17.400000000,2017-03-09 08:10:17.400000000,62.439999,2017-03-08,2017-03-16
56189_1_1,56189,1,1,2017-03-09 08:54:16.200000000,2017-03-09 09:33:16.200000000,43.980000,2017-03-08,2017-03-16
55764_1_1,55764,1,1,2017-03-09 10:17:14.400000000,2017-03-09 10:45:14.400000000,43.980000,2017-03-08,2017-03-16
55589_1_1,55589,1,1,2017-03-09 11:47:40.800000000,2017-03-09 12:15:40.800000000,62.439999,2017-03-08,2017-03-13
56253_1_1,56253,1,1,2017-03-09 13:18:30.000000000,2017-03-09 13:48:30.000000000,62.810001,2017-03-08,2017-03-15
56224_1_1,56224,1,1,2017-03-09 14:50:56.400000000,2017-03-09 17:05:56.400000000,62.439999,2017-03-08,2017-03-14
55587_1_1,55587,1,1,2017-03-09 18:08:22.799999999,2017-03-09 18:36:22.799999999,62.439999,2017-03-08,2017-03-13
55853_1_1,55853,1,1,2017-03-09 19:38:49.200000000,2017-03-09 20:31:49.200000000,62.439999,2017-03-08,2017-03-17
55586_1_1,55586,1,1,2017-03-09 21:37:34.200000000,2017-03-09 23:01:34.200000000,65.750000,2017-03-08,2017-03-13
56256_1_1,56256,1,1,2017-03-10 00:00:12.000000000,2017-03-10 00:33:12.000000000,58.630001,2017-03-09,2017-03-20
56259_1_1,56259,1,1,2017-03-10 01:44:28.200000000,2017-03-10 02:18:28.200000000,71.269997,2017-03-09,2017-03-20
55945_1_1,55945,1,1,2017-03-10 03:21:58.799999999,2017-03-10 03:58:58.799999999,63.509998,2017-03-09,2017-03-20
56354_1_1,56354,1,1,2017-03-10 04:50:40.800000000,2017-03-10 05:19:40.800000000,51.700001,2017-03-09,2017-03-17
55922_1_1,55922,1,1,2017-03-10 06:16:16.200000000,2017-03-10 06:46:16.200000000,56.590000,2017-03-09,2017-03-20
56255_1_1,56255,1,1,2017-03-10 07:51:25.200000000,2017-03-10 11:07:25.200000000,65.150002,2017-03-09,2017-03-20